### ISSUE TITLE
Current ToDo

### ISSUE THREAD

**Issue by k2kobayashi** [k2kobayashi/sprocket#93]
### ToDo
- [ ] Create document and open at GitHub.io?
- [ ] Register PyPI
- [ ] Test using VCC 2018 dataset 
- [ ] Devide sprocket library and sprocket-examples into different repository

### Function implementation
- [ ] Single-path training
- [ ] Alignment with silence and 0-th order of mel-cepstrum
- [ ] Implement EL or NAM to SP example scripts
